version: '3'
services:

  hotels:
    build:
      context: ./
      dockerfile: Dockerfile
    image: php-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: hotels
      SERVICE_TAGS: dev
    working_dir: /var/www
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    networks:
      - default